import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/layout";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello world</h1>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    </Layout>
  );
}
