import Head from "next/head";
import Layout from "@/components/layout";
import NewsList from "@/components/newslist";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

const darkTheme = createTheme({
  palette: {
    mode: "dark",
  },
});

// TODO: create a paginator with nextjs router
// TODO: work on news types
export async function getServerSideProps(context: any) {
  const res = await fetch(`https://hacker-news.firebaseio.com/v0/topstories.json`);
  const topIds = await res.json();
  const reqTopStories: any[] = await topIds.slice(0, 10).map(async (id: number) => {
    const res = await fetch(`https://hacker-news.firebaseio.com/v0/item/${id}.json`);
    const story = await res.json();
    return story;
  });
  const topStories = await Promise.all(reqTopStories);
  return {
    props: {
      topStories: topStories,
    },
  };
}

export default function Home({ topStories }: any) {
  return (
    <ThemeProvider theme={darkTheme}>
      <CssBaseline />
      <Layout>
        <Head>
          <title>Hacker news</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NewsList list={topStories} />
      </Layout>
    </ThemeProvider>
  );
}
